# Generated by Django 6.0.5 on 2026-05-23 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listinginquiry',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_records', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='listinginquiry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingview',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='listingview',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['listing', 'viewed_at'], name='listings_li_listing_df08d5_idx'),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['viewer', 'viewed_at'], name='listings_li_viewer__1a1b7e_idx'),
        ),
    ]
